apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "shield.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- if .Values.labels }}
    {{- toYaml .Values.labels | trim | nindent 4 }}
  {{- end }}
data:
  {{- toYaml .Values.config | nindent 2 }}
