apiVersion: v1
kind: Service
metadata:
  name: {{ template "shield.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | trim | nindent 4 }}
    {{- end }}
  {{- if .Values.service.annotations }}
    run: {{ .Release.Name }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerSourceRanges}}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end}}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end}}
      protocol: TCP
      name: {{ template "shield.name" . }}
  selector:
    run: {{ .Release.Name }}
