apiVersion: v1
kind: Service
metadata:
  name: {{ template "raccoon.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | trim | nindent 4 }}
    {{- end }}
    run: {{ .Release.Name }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.service.clusterIP }}  
    clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.raccoon.config.SERVER_WEBSOCKET_PORT }}
  selector:
    app: {{ include "raccoon.fullname" . }}
